### ISSUE TITLE
replace terraform with tfswitch

### ISSUE THREAD

**Issue by pjungermann** [pjungermann/mac-setup#10]
tfswitch allows to support and use multiple terraform versions at the same time and identified the necessary version for run folder using the version constraints in `versions.tf`. Necessary terraform versions get installed by it on-the-fly.

Optional: It may make sense to preinstall the latest version or allow to choose which one to install. (see also issue #9)

**Comment by kvendingoldo** [comment]
btw. you can also use [tenv](https://github.com/tofuutils/tenv) that support Terraform as well as OpenTofu (and Terragrunt :) ) in one tool. It allow you to simplify version management and can do much more, than tfswitch.
